
class CommonDefs:
    INDEX_OF_OHLC_DATA = 0
    INDEX_OF_CANDLESTICK_PLOT_DATA = 1
    INDEX_OF_MA_DATA = 2
    INDEX_OF_STOCHASTICS_DATA = 3
    INDEX_OF_WILLIAMS_DATA = 4
    INDEX_OF_MOMENTUM_DATA = 5
    INDEX_OF_DATE_INDEX = 6
    INDEX_OF_MACD_DATA = 7